# Generated by Django 4.0.4 on 2022-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug_ticket',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
