# Generated by Django 4.0.4 on 2022-05-29 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugTrackerApp', '0004_extendeduser_bio_extendeduser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='ogUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
