# Generated by Django 4.0.4 on 2022-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0005_alter_extendeduser_oguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
