# Generated by Django 4.0.4 on 2022-05-30 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugTrackerApp', '0006_extendeduser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_ticket',
            name='developers',
            field=models.ManyToManyField(blank=True, null=True, related_name='developers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug_ticket',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='bugTrackerApp.tag'),
        ),
    ]
