# Generated by Django 4.0.4 on 2022-05-31 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugTrackerApp', '0007_alter_bug_ticket_developers_alter_bug_ticket_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_ticket',
            name='developers',
            field=models.ManyToManyField(limit_choices_to={'extendeduser__bDev': True}, related_name='developers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug_ticket',
            name='tag',
            field=models.ManyToManyField(to='bugTrackerApp.tag'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='profilePicture',
            field=models.ImageField(upload_to=''),
        ),
    ]
