# Generated by Django 4.0.4 on 2022-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0008_alter_bug_ticket_developers_alter_bug_ticket_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
