# Generated by Django 4.0.4 on 2022-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0009_alter_extendeduser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
