# Generated by Django 4.0.4 on 2022-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0010_alter_extendeduser_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
