# Generated by Django 4.0.4 on 2022-07-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0012_remove_extendeduser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='profilePicture',
        ),
    ]
