# Generated by Django 4.0.4 on 2022-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTrackerApp', '0013_remove_extendeduser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_ticket',
            name='tag',
            field=models.ManyToManyField(blank=True, to='bugTrackerApp.tag'),
        ),
    ]
